#!/bin/bash
VERSION=`git describe --tags | sed 's|-\(.*\)-.*|.\1|'`
VERSION="${VERSION:1}"
echo "Inferred version: $VERSION"
echo "Checking configure await..."
if ! ./checkConfigureAwait; then
    exit 1
fi
cp WorkerPool.nuspec.template WorkerPool.nuspec
sed -i "s|<version>.*</version>|<version>$VERSION</version>|" WorkerPool.nuspec
sed "s|@VERSION|$VERSION|g" SystemConstants.template > WorkerPool/WorkerPool/SystemConstants.cs
sed "s|@VERSION|$VERSION|g" VersionAssemblyInfo.template > WorkerPool/WorkerPool/VersionAssemblyInfo.cs
#nuget restore
build.bat
mkNugetPkg
